### ISSUE TITLE
background: linear-gradient issue?

### ISSUE THREAD

**Issue by tchibomann** [csstree/csstree#13]
Hi!

First of all: really nice tool!

I think i have found a bug, maybe. The tool found a mismatch, which is no mismatch at all:

> Unique properties: 93
> Unique declarations: 550 (total: 1228)
>   ✓ Valid:   548 (99.64%)
>   ✗ Invalid: 2 (0.36%)
>       2 × Mismatch
> Mismatch
>   syntax: [ <bg-layer> , ]* <final-bg-layer>
>   background: linear-gradient(top,rgba(255,255,255,0.9),rgba(255,255,255,1) 20%)
>   ------------^
> Mismatch
>   syntax: [ <bg-layer> , ]* <final-bg-layer>
>   background: linear-gradient(top,rgb(0,0,0),rgb(18,18,18) 100%)
>   ------------^

css:
`.site-footer {
    margin-top: 0rem;
    background: #121212;
    background: -webkit-linear-gradient(top, rgb(0, 0, 0), rgb(18, 18, 18) 100%); /* Chrome, Safari */
    background: -moz-linear-gradient(top, rgb(0, 0, 0), rgb(18, 18, 18) 100%); /* Firefox */
    background: linear-gradient(top, rgb(0, 0, 0), rgb(18, 18, 18) 100%); /*  CSS3 */
}`

Can you check that?

Cheers!
Patrick

**Comment by lahmatiy** [comment]
According to spec `linear-gradient()` should contains `to` (or `at` for radial gradients) keyword for directions. Initial version of spec was without `to` keyword and many browsers implemented their prefixed versions with no `to` keyword. But unprefixed version requires `to` and doesn't work otherwise. More details: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#History_of_the_syntax
Your style works because fallbacks to prefixed gradients. Screenshot from Chrome:
![image](https://cloud.githubusercontent.com/assets/270491/18469714/dd005366-79b1-11e6-8002-db55a983a39c.png)
So you need add `to` keyword into your unprefixed gradients.
Truly speaking it's a most common mistake I met during testing.

**Comment by tchibomann** [comment]
Ah damn! Didn't know that. Maybe it's a good idea to improove the message that has been displayed for this mismatch?

Many thanks for your help!

**Comment by lahmatiy** [comment]
Well, I'm planing to show suggestions, may be custom messages for most common issues like this one and more. But latter, because it's actually a side effect of my work on CSS syntax parser :)
