### ISSUE TITLE
Please republish alpha.39 as beta.1

### ISSUE THREAD

**Issue by arcanis** [csstree/csstree#134]
Earlier tags were of the form `alpha9` (compare with the current `alpha.39`, which features a dot). The problem is that, per semver spec, it makes `alpha9` a *higher* version than `alpha.39`:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
>
> - Identifiers consisting of only digits are compared numerically.
> - Identifiers with letters or hyphens are compared lexically in ASCII sort order.
> - Numeric identifiers always have lower precedence than non-numeric identifiers.
> - A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

Since `alpha` < `alpha9` in the ASCII sort order, the semantically highest version on the registry is `1.0.0-alpha9`... Since package managers may install the highest available release, in some cases they'll install the four-years old. The fix is fortunately simple: please just republish the last build with `beta.1`, which will resolve the ambiguity.

Ref https://github.com/npm/node-semver/issues/335, https://github.com/yarnpkg/berry/issues/1548 (after digging, it turns out `semver` is technically correct, and the problem comes from css-tree).

**Comment by strarsis** [comment]
@lahmatiy: Yes, please publish a beta release. This library is in use for very long time, also in `svgo` and optimized countless of SVG files. Its alpha releases also cause concern in the inclusion in other projects like Gutenberg because `alpha` correctly indicates an unstable version.

**Comment by ext** [comment]
Got hit by this issue as well when using renovate bot, it would try to downgrade to `1.0.0-alpha9` instead of keeping it at `1.0.0-alpha.39`.

**Comment by strarsis** [comment]
@lazarljubenovic: Why the downvote?

**Comment by lazarljubenovic** [comment]
@strarsis Because I disagree with the comment.

**Comment by strarsis** [comment]
@lazarljubenovic: But why isn't it a good idea to consider and publish this library at least as beta after so many years of its usage in different tools that process large amounts of CSS, hence unreliabilities should have been found out long ago?

**Comment by ext** [comment]
> @strarsis Because I disagree with the comment.

I'm also a bit curious about what you disagree with. Just downvoting without a reason explaining why seems a bit rude to me.

[Alpha versions](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha) to me are unstable by nature but since this is used by some large libraries and not under active development it makes sense to me to publish a proper release.

**Comment by lahmatiy** [comment]
Hi all!
Sorry for delay in response.
First of all, let me clarify the alpha stage of the project. The library looks stable and mature enough. However, there are number of uncompleted improvements and breaking changes that I believe must be in CSSTree. Unfortunately I have no time currently to finish this work on the project. So alpha stage was a signal that everything (API, AST format, etc) may change with no ETA.
At the same time, the number of dependant projects and downloads are growing. And, surprisingly, there are no so many bugs or issues reported since the last release 10 months ago. Also I agree that `alpha` version may be confusing and frustrating despite its usage by many project.
So I decide to fork a branch from last release, cherry pick some non-breaking changes and release it as 1.0.0 (with no any prefix). There are number of changes on master that aren't published yet, they will be shipped as 2.0 when done.

**Comment by strarsis** [comment]
@lahmatiy: Will css-tree 1.0.0 be released (also to npm) in the near future?

**Comment by lahmatiy** [comment]
@strarsis Yes, I'm going to publish it this weekends.

**Comment by lahmatiy** [comment]
Just published [1.0.0](https://github.com/csstree/csstree/releases/tag/v1.0.0) 🎉
