### ISSUE TITLE
Failure parsing comma literal with multipliers

### ISSUE THREAD

**Issue by pyoor** [csstree/csstree#138]
CSS-Tree fails to parse comma literals when a multiplier is specified.  I.e. `,?` or `,#`

It throws with the following stack:
```
Uncaught TypeError: Cannot set property stack of SyntaxError: Unexpected input
  ,  #
-----^ which has only a getter
    at Domain.debugDomainError (repl.js:541:21)
    at Domain.emit (events.js:315:20)
    at Domain.EventEmitter.emit (domain.js:482:12)
    at REPLServer.defaultEval (repl.js:454:26)
    at bound (domain.js:426:14)
    at REPLServer.runBound [as eval] (domain.js:439:12)
    at REPLServer.onLine (repl.js:760:10)
    at REPLServer.emit (events.js:327:22)
    at REPLServer.EventEmitter.emit (domain.js:482:12)
    at REPLServer.Interface._onLine (readline.js:329:10)
```

This was identified in the [SVGWG Animation Spec](https://svgwg.org/specs/animations/#DataTypeControlPoint).  As far as I can tell, this is valid syntax.

**Comment by lahmatiy** [comment]
According to CSS Definition Syntax multipliers are never used with comma or other delimiters. Syntax used in Animation Spec is close to CSS Definition Syntax, however it has incompatible differences. I have not found any reference to CSS Definition Syntax in the spec, so I'm not sure that's the same syntax. Also there are some notes `Attribute syntax needs fixing` in the spec, so some issues may be a mistake.
I believe no fixes needed at the moment. Since all [CSSWG specs syntaxes are parsing well](https://csstree.github.io/csswg-drafts-index/#report&noedit&title=Problem%20syntaxes&q=KGRlZnMgKyBwcm9kcykKLmdyb3VwKDxkZWZpbml0aW9uU3ludGF4LmVycm9yIG9yIGRlZmluaXRpb25TeW50YXgudmFsdWUuZXJyb3I%2BKS5ba2V5XQo%3D&v=ewogICAgdmlldzogJ2xpc3QnLAogICAgaXRlbTogewogICAgICAgIHZpZXc6ICdleHBhbmQnLAogICAgICAgIGV4cGFuZGVkOiB0cnVlLAogICAgICAgIHRpdGxlOiAncHJlOmtleScsCiAgICAgICAgY29udGVudDogewogICAgICAgICAgICB2aWV3OiAnbGlzdCcsCiAgICAgICAgICAgIGRhdGE6ICd2YWx1ZScsCiAgICAgICAgICAgIGl0ZW06ICdkZWYnCiAgICAgICAgfQogICAgfQp9) (except for those with mistakes) and SVGWG specs are out of scope until explicit using CSSDS.

Btw `,#` is 1 or more comma separated by a comma ;)
