### ISSUE TITLE
How to use with PostCSS?

### ISSUE THREAD

**Issue by joelmoss** [csstree/csstree#141]
I've been unable to find out how to use csstree as the parser in PostCSS. PostCSS has a `parser` option, but passing `'css-tree'` to that doesn't work, and spits out this error:

```
TypeError: Cannot read property 'length' of undefined
    at MapGenerator.clearAnnotation (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/map-generator.js:68:34)
    at MapGenerator.generate (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/map-generator.js:273:10)
    at LazyResult.stringify (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/lazy-result.js:228:20)
    at LazyResult.runAsync (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/lazy-result.js:370:17)
    at LazyResult.async (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/lazy-result.js:178:30)
    at LazyResult.then (/Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss/lib/lazy-result.js:163:17)
    at /Users/joelmoss/dev/rails_esbuild_play/node_modules/postcss-cli/index.js:220:10
```

Can anyone help please?

**Comment by ludofischer** [comment]
According to the [documentation](https://github.com/postcss/postcss/blob/master/docs/syntax.md), a PostCSS parser must implement a specific API. The first thing I notice is that the function called `generate()` in CSSTree should be called `stringify()`. You could try creating a wrapper around CSSTree, but there might still be issues if the AST format is too different from what PostCSS expects.

**Comment by joelmoss** [comment]
Well now I'm a little confused, as there is a [PostCSS benchmark](https://github.com/postcss/benchmark) for csstree, so surely that should mean that csstree will work with PostCSS?

**Comment by deflock** [comment]
> so surely that should mean that csstree will work with PostCSS?

No, it shouldn't. In that benchmark postcss compares its own parser to others.
You can see supported parsers here: https://github.com/postcss/postcss#syntaxes

**Comment by joelmoss** [comment]
Ah right. Makes sense now. Would be great if csstree did support postcss. Or the other way around 😏

Thx anyway

**Comment by lahmatiy** [comment]
I'm not sure such integration makes sense. However, technically that's possible. I did AST transformation csstree -> postcss and back in wrapper for CSSO:
https://github.com/lahmatiy/postcss-csso

**Comment by lahmatiy** [comment]
This discussion has remained open, although the initial question was answered and I have a position on "csstree should has a support of postcss".

An integration with PostCSS or anything else is not a responsibility of CSSTree or any other such kind of libraries. If any integration is needed, there should be an adapter or something like that which deals with it. In other words, that's a subject for a project (a library) aside which solves such a problem. In case, someone wants to make a CSSTree <-> PostCSS integration library, a [postcss-csso](https://github.com/lahmatiy/postcss-csso) codebase is a good start. If such projects appear, I will be happy to add a link to them into readme and docs. I don't have the resources or interest to work on a project like this, sorry. That's why I close the issue with "won't fix".
