### ISSUE TITLE
Parser Build with limited syntax support?

### ISSUE THREAD

**Issue by bramus** [csstree/csstree#183]
Winging over from https://github.com/stylelint/stylelint/issues/5065#issuecomment-1049786717, I'm wondering if it's possible to make a build of the CSSTree parse with limited syntax support, such as only supporting `SelectorList`.

That way, the bundle contained in projects such as https://github.com/bramus/js-specificity can be shrunk down further, as it wouldn't include the entire list of properties, color names, etc.

**Comment by lahmatiy** [comment]
> wouldn't include the entire list of properties, color names, etc

As I mentioned in the referenced thread, a wrong version of js-specificity was examined. Starting with js-specificity 1.0.5, a bundle doesn't include a syntax definition dictionary. So that's not an issue.

> I'm wondering if it's possible to make a build of the CSSTree parse with limited syntax support, such as only supporting SelectorList.

Yes, it's possible. My quick and dirty experiment demonstrated that a bundle size of CSSTree parser (a parser's size in the bundle) which specialized on a selector parsing only can be reduced by ~50%. Your feature request is clear and reasonable to me. I can't say for sure about ETA, but I'm going to add such entry point (a selector's only parser) in the next release.

**Comment by lahmatiy** [comment]
Fixed in [2.1.0](https://github.com/csstree/csstree/releases/tag/v2.1.0) by adding `css-tree/selector-parser` export which is ~27kb instead of ~50kb. The general purpose parser is also reduced in size to 41kb.
