### ISSUE TITLE
background-clip should allow value `text`

### ISSUE THREAD

**Issue by carlosjeurissen** [csstree/csstree#190]
I'm getting errors with:
```
background-clip: text;
```

**Comment by lahmatiy** [comment]
That's a little bit tricky. Most browsers are supported `background-clip: text` unprefixed. However, this not on [msd-data](https://github.com/mdn/data), because it added only in [CSS Backgrounds and Borders Module Level 4](https://drafts.csswg.org/css-backgrounds-4/) which has a warning "Not Ready For Implementation". Anyway, we can add it to [patch.json](https://github.com/csstree/csstree/blob/master/data/patch.json) until it added to mdn-data. Do you want to make a PR?

Until this is fixed in `css-tree`, if you use `css-tree` directly, you can fix the problem with the `fork()` method.
