### ISSUE TITLE
@page should not require prelude

### ISSUE THREAD

**Issue by carlosjeurissen** [csstree/csstree#191]
The following code:
```
@page {
  size: landscape;
}
```

Gives the error: At-rule should contain a prelude. As far as I know @page without anything is valid.

**Comment by lahmatiy** [comment]
You are right, that's a bug – a prelude should be optional.

At the moment, the problem is that there were no such cases before (yes, it was always for `@page`, but I missed it) and in the rules for the lexer there is no way yet to indicate that the prelude can be optional. So the fix may not be as simple as I would like. Can't say ETA, but it would be fixed.
