### ISSUE TITLE
`.2.3rem` Shouldn't Be Compliant

### ISSUE THREAD

**Issue by shellscape** [csstree/csstree#194]
AFAIK `.2.3rem` is a non-compliant value, but css-tree lets it pass.

```js
import { parse, walk } from 'css-tree';

const value = '.2.3rem';
const ast = parse(value, { context: 'value', positions: true });

console.log(ast.children.toArray());
```

**Comment by lahmatiy** [comment]
It may look odd, but this is the correct value in general from the perspective of CSS. It which consists of 2 tokens `<number-token>` and `<dimension-token>`. Since these tokens in this particular case don't produce a new token, a white space between them is not necessary. However, css-tree adds a whitespace according to a spec. This is defined by the spec for simplicity, because in some case such tokens might produce a single token (e.g. `.2` and `3em`) and determining when it is safe not to put a space, and when it is required, is too complicated.
However, mixing numbers and dimensions in a value is a pretty rare case. Therefore, if you apply a property syntax definition to such a value (you need a [syntax matching API](https://github.com/csstree/csstree#usage) for this), there will certainly be an error.

**Comment by shellscape** [comment]
Interesting. The bit that throws me off here is the `.` that separates `.2` and `3`. Is that treated as whitespace by the spec, or is the trailing `.` discarded by the spec due to the leading `.`?

**Comment by lahmatiy** [comment]
There are 2 tokens: `.2` and `.3em`. Numbers can contain only one `.`. You can try to tokenize the value using css-tree tokenizer (or any spec compliant tokenizer):

```js
import { tokenize, tokenNames } from 'css-tree';

const value = '.2.3rem';
tokenize(value, (type, start, end) => {
    console.log(tokenNames[type], value.slice(start, end));
});
// number-token .2
// dimension-token .3rem
```

**Comment by shellscape** [comment]
Really interesting, thanks for elaborating.
