### ISSUE TITLE
Allow Correction for `fallbackNode` in `onParseError`

### ISSUE THREAD

**Issue by shellscape** [csstree/csstree#196]
It would be incredibly handy, and serve as a point of extensibility, if users had the ability to mark a `fallbackNode` as OK, or to return a Node type that could otherwise be inserted into the AST when `onParseError` occurs.

Use case:

I'm porting my package `postcss-values-parser` over to use `css-tree` instead of a homebrew tokenizer, and I've long supported options for parsing that instruct the parser to ignore unknown words (like `@foo`) and allow users to set custom variable prefixes (like `$$batman`, for SASS, LESS, etc). Currently, css-tree doesn't know what to do with those, as they aren't spec compliant.

**Comment by lahmatiy** [comment]
`fallbackNode` and `onParseError` are parts of the parser, not tokenizer. A tokenizer produces tokens, a parser constructs a AST from tokens. A CSS tokenizer may not be suitable for SASS/Less/etc parsing, you might need to introduce some additional token types to simplify assembling a AST. However, it's possible in theory without new token types (to build AST for *-processor using CSS only tokens).
css-tree has `fork()` method to create a fork of default setup with some extensions/overrides, mostly in parser & lexer (it doesn't allow to extend token types for instance, because it's too complicated). I tried it in [stylelint-validator](https://github.com/csstree/stylelint-validator). There are basic extensions for [SASS](https://github.com/csstree/stylelint-validator/blob/master/lib/syntax-extension/sass/index.js) and [LESS](https://github.com/csstree/stylelint-validator/blob/master/lib/syntax-extension/less/index.js), and [here](https://github.com/csstree/stylelint-validator/blob/master/lib/index.js#L13-L20) they are used.

**Comment by lahmatiy** [comment]
Revisiting the issue, I believe having control over `fallbackNode` seems like a good opportunity. However, it doesn’t work well in practice, as you often need the parser’s context (i.e., where the parser is currently located), and providing that context is challenging.

As an alternative solution, you could store `fallbackNode`s using the `onParseError` callback, then walk through the AST to replace the target nodes based on your needs. This approach seems more straightforward, as it gives you all the context needed to make decisions.
