### ISSUE TITLE
Url Modifiers

### ISSUE THREAD

**Issue by shellscape** [csstree/csstree#197]
In my ongoing efforts for postcss-values-parser I ran across a unit test that attempts to process `url(var(foo))`. I had previously tokenized and parsed this as valid CSS. It appears to be somewhat of a grey area, as MDN denotes url-modifiers as experimental, but they do exist on the spec https://drafts.csswg.org/css-values/#typedef-url-modifier:

> The [url()](https://drafts.csswg.org/css-values/#funcdef-url) function supports specifying additional <url-modifier>s, which change the meaning or the interpretation of the URL somehow. A [<url-modifier>](https://drafts.csswg.org/css-values/#typedef-url-modifier) is either an [<ident>](https://drafts.csswg.org/css-values/#typedef-ident) or a [functional notation](https://drafts.csswg.org/css-values/#functional-notation).
> 
> This specification does not define any [<url-modifier>](https://drafts.csswg.org/css-values/#typedef-url-modifier)s, but other specs may do so.

So it's basically "we don't say what the valid url modifiers are, but we're leaving the spec wide open for modifiers to be used." Hence the grey area. Is this something you would be comfortable supporting?

_Aside_

Supporting url-modifier would also mean supporting something like `url("/gfx/img/bg.jpg" hello )` and `url("/gfx/img/bg.jpg" hello() )`

**Comment by lahmatiy** [comment]
Truly speaking that's not a grey zone at all. To assemble a puzzle, you need to put together different pieces from 3 specs:

### [CSS Syntax Module](https://www.w3.org/TR/css-syntax-3)

This spec is about general rules for CSS parsing. It claims that `url(...)` (unquoted syntax) is not the same as `url("...")`  or `url('...')` (quoted syntax). First one is a legacy syntax and there is a dedicated token type for it `<url-token> ` (and counterpart `<bad-url-token>`) as well as a specific algorithm to parse it, see [Consume a url token](https://www.w3.org/TR/css-syntax-3/#consume-url-token). In short, the unquoted syntax is a monolith value, i.e. `url(foo/bar)` is a single. To extract a URL you need to get a substring from token's value (e.g. something like `token.slice(4, -1).trim()`).

Opposite to it, a quoted syntax is a modern one and parsed as a regular function, so it starts with `<function-token>` (always `url(`) and ends with `<)-token>`, zero or more tokens might be between, nothing else. Quote from the spec:

> Note: This algorithm assumes that the initial "url(" has already been consumed. This algorithm also assumes that it’s being called to consume an "unquoted" value, like url(foo). A quoted value, like url("foo"), is parsed as a [`<function-token>`](https://www.w3.org/TR/css-syntax-3/#typedef-function-token). [Consume an ident-like token](https://www.w3.org/TR/css-syntax-3/#consume-an-ident-like-token) automatically handles this distinction; this algorithm shouldn’t be called directly otherwise.

### [CSS Values and Units Module](https://www.w3.org/TR/css-values-4/)

This spec defines a structure of quoted syntax for `url()` and `src()` functions. All details in [Resource Locators: the `<url>` type](https://www.w3.org/TR/css-values-4/#url-value) section:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/270491/178854290-c213c3ec-27ab-4198-9a68-0b81facc538c.png">

Regarding to this section `url(var(--foo))` explicitly stated as invalid. Later on, in the next paragraph, you can find:

> The unquoted [url()](https://www.w3.org/TR/css-values-4/#funcdef-url) syntax cannot accept a [`<url-modifier>`](https://www.w3.org/TR/css-values-4/#typedef-url-modifier) argument and has extra escaping requirements: ...

There are also some more detail and a back reference to CSS Syntax Module.

As I see it, you probably think that `url(var(--foo))` is about using a `<url-modifier>` in `url()`, but it's not. Such value is invalid just because a `<string>` is missed. Just check the definition for `<url>` – a `<string>` is required (no any multiplier is applied, but applied for `<url-modifier>`): `url( <string> <url-modifier>* )`.

Nevertheless, I think you should wondering why `src(var(--foo))` is valid (see the first screenshot), but `url(var(--foo))` is not. That's why...

### [CSS Custom Properties for Cascading Variables Module](https://www.w3.org/TR/css-variables-1/)

At first glance this spec is "nothing special". However that's a game changer. Because of this:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/270491/178859244-3d16baba-6d30-4c7a-9130-b41a8a641ab2.png">

So using `var(--foo)` inside of a value is not about a string substitution but a substitution of list of tokens. However, most important thing you should know about `var()` is described in this paragraph:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/270491/178859537-f84ea562-a97a-48d7-853b-97455d253452.png">

In general, when a value contains `var()` it can't be evaluated until `var()` value (a token list) is substituted. Moreover, everything around `var()` should be kept as token lists as well. In other words, a value `...var(--foo)...var(--bar)...` can be parsed only as `[TokenList(...), <var>, TokenList(...), <var>, TokenList(...)]`. You can't assemble AST until all vars are substituted. For instance, that's a valid CSS that works in case `foo` and `bar` classes are set on the same element:

```css
.foo {
  --example: , 2);
}
.bar {
  transform: scale(1 var(--example);
}
```

Ok, usually nobody writes CSS like this. However, that's a valid CSS per spec which works in any browser today.

Let's back to `url(var(--foo))` and `src(var(--foo))`. What's difference here? Well, since `url()` doesn't start with a quote a parser should fall back to the legacy (unquoted) syntax parsing. In this case `url(var(--foo))` tokenized as a single token, so `var(...)` is a part of `url()`:

```
<url-token> "url(var(--foo))"
```

On other hand `src(...)` is parsed as a regular function, so a tokenizer should emit:

```
<function-token> "src("
<function-token> "var("
<ident-token> "--foo"
<)-token> ")"
<)-token> ")"
```

So the `var()` function can be detected which prevents a value processing until all `var()` are substituted in and matched to a declared grammar. That's it.

---

### Conclusion

Supporting for `<url-modifier>` is not a big deal from the perspective of the parser and AST. However, there are no details yet on how this might be used in practice, and no single browser supports it. At the same time, `url(var(--foo))` notation has nothing common with it.

**Comment by shellscape** [comment]
This is a fascinating read. It's so valuable it should really be a blog post! Thanks for writing this up. I have questions, but I'm going to sleep on it and come back to it in the morning.

**Comment by shellscape** [comment]
After sleeping on this, and taking another pass at a reading, it makes complete sense per spec. The section above this line

> Regarding to this section url(var(--foo)) explicitly stated as invalid. 

was really the key. Based on this and discussion in #196, I'll be going to route of spec-compliance first which will remove a lot of features from the package (but it's a major version so it'll be fine initially). Once I've got it stable, I'll look into the suggestions on #196 for enabling a non-spec-compliant mode.

**Comment by anobjectn** [comment]
**Specifying Images in Custom Properties in Style Attributes, Practical considerations**
I've been specifying images in custom properties in style attributes as this is a convenient pattern for merging images selected in a CMS to a ui, and using media queries to select which image is rendered. I have been omitting quotes because Google published it as a best practice. 

` style="--img-xl: url(https://mysite.com/wp-content/uploads/2024/01/dining4_lg-1600x848.jpg); --img-xxl: url(https://mysite.com/wp-content/uploads/2024/01/dining4_lg.jpg);"`

however, it looks like all assets are downloaded. this is not what I want. Has anyone found a good pattern that merges image paths in the markup with responsive CSS in a more performant way?
