### ISSUE TITLE
[Feature request] Store whitespaces, lossless generation

### ISSUE THREAD

**Issue by scripthunter7** [csstree/csstree#212]
CSSTree currently does not store whitespaces, so it is not possible - for example - to check formatting or generate nodes in "lossless" mode. Obviously, there may be edge cases, so a completely lossless generation is probably not possible, but the preservation of whitespaces can be considered. If I understood correctly, the tokenizer handles the whitespaces, just the parser currently ignores them.

My idea is that the parser's options object gets a `whitespaces` / `lossless` property or something, which specifies that the AST stores the whitespaces (spaces, tabs). I know this can have a negative effect on performance / memory, so I thought it would be optional.

There is a similar feature in PostCSS: it stores whitespaces in `before` and `after` properties. Reference: https://postcss.org/api/#atrule-raws

_Note:_ CSSTree stores node positions, which could _theoretically_ be used during generation, but as far as I can see it does not store the type of whitespaces (space / tab, etc).

@lahmatiy Do you support such an idea? If so, I can even help with the implementation

Lossless-related: https://github.com/csstree/csstree/issues/211

**Comment by lahmatiy** [comment]
@scripthunter7 I don't support the idea at the moment. I thought about it a lot, and even filled a related issue https://github.com/csstree/csstree/issues/78 some years ago. However, it looks to me as a "mission impossible" for now. So yeah, we can try. But looking around on attempts in other libraries and languages, I see it as too much complexity into AST processing so I doubt it worth it. When I'm mentioning problems, I mean attaching whitespaces and comments to a right nodes, as well as handling them on a AST transformations etc.

PostCSS has much simpler AST structure. For PostCSS is much easier to keep formatting since it doesn't parse selectors, at-rule preludes and declaration's values. Even in such conditions a preserving original formatting is connected with hacks and caveats.

**Comment by scripthunter7** [comment]
I'm leaving the issue open for now, and I'm thinking about what kind of data structure would be ideal. I've closed the quote mark issue / PR, it will come up naturally on this line anyway.

**Comment by lahmatiy** [comment]
I don't think that's a good idea to have a duplicate issues. I propose to close this issue because of #78. When you have ideas and suggestions, you can add them there. Agree?

**Comment by scripthunter7** [comment]
Agree:)
