### ISSUE TITLE
CSSTree does not differentiate between `<compound-selector>` and `<complex-selector>`

### ISSUE THREAD

**Issue by bramus** [csstree/csstree#214]
Some pseudos – such as [`::slotted()`](https://w3c.github.io/csswg-drafts/css-scoping/#slotted-pseudo) – accept a `<compound-selector>` as its argument.

`::slotted(foo bar)` for example should not parse, yet CSSTree accepts the `<complex-selector>` just fine.

Demo: https://codepen.io/bramus/pen/xxzNjaQ/b1a9b2c54cfdd5ca007bcbedb4b6c32e

**Comment by lahmatiy** [comment]
That's correct, CSSTree does not differentiate between various types of selector for several reasons:
- Simplification. There are a lot of types of selectors, but for processing (e.g. a specificity calculation) and analysis it usually doesn't make sense. In other words, it much easier to deal with `SelectorList` and `Selector` node types instead of a bunch of types like `ComplexSelector`, `CompoundSelector`, `RelativeSelector`, `ForgivingSelector`, `ForgivingRelativeSelector` etc. and their `*List` counterparts (i.e. `RelativeSelectorList`). So you will need to enumerate all the types in node type check conditions:
```js
if (node.type === 'ComplexSelector' || node.type === 'CompoundSelector' || ...) {
    // ...
}
```
- Performance and memory consumption. Introducing all the types will bloat AST as well, e.g. instead of:
```
SelectorList
    Selector
        TypeSelector
        Combinator
        PseudoClassSelector
```
you will get
```
ComplexSelectorList
    ComplexSelector
        CompoundSelector
            TypeSelector
        Combinator
        CompoundSelector
             PseudoClassSelector
```
That's more deeper structure and more objects (nodes) to build, which means more memory is needed for AST and slower parsing. AST transformation and building become more complicated as well.
- Hard to align with specs. CSS specs are changing, as well as allowed types in various contexts. For instance, originally `:not()` was allowed to take a complex selector. In next level this functional pseudo class was extend to take a complex selector list. What is correct? It depends on your CSS target - is it legacy (old spec) or modern browsers.
- CSSTree tries to be as much tolerant as possible. In this case you can analyse a structure of selector, propose a changes or auto-fix, transform it in a correct form etc. using AST. Otherwise you will have just a string which you will need again to parse somehow.
- Decoupling responsibilities. CSSTree's parser does it best to provide AST, its primary goal. Validation rules are pretty complex and depends on many factors like specs status and context. A validation on parsing is not always needed, make it complex and slowing it down. So validation should be optional and aside. The lexer functionality is used for such purposes. For now lexer provides functionality to validate property's values and at-rules. For now it doesn't support a validation for selectors, but I believe it should implemented in the lexer.

**Comment by bramus** [comment]
Thanks for the feedback, understand the reasoning here.

How could selector validation be implemented in the lexer? Took a quick look but don’t immediately see how it would work. Got some pointers or a basic snippet which I can base myself on?
