### ISSUE TITLE
Pseudos that require an argument parse fine, although they shouldn’t

### ISSUE THREAD

**Issue by bramus** [csstree/csstree#215]
The `:has` selector for example requires an argument. CSSTree however parses `:has` just fine. It should not, as the syntax for [this selector](https://w3c.github.io/csswg-drafts/selectors/#relational) is `:has(<relative-real-selector-list>)`

Demo: https://codepen.io/bramus/pen/bGKyMOB

Trying to parse `:has()` does throw, correctly requiring a selector.

**Comment by lahmatiy** [comment]
The same answer as for https://github.com/csstree/csstree/issues/214 - a validation of selectors is not a subject for the parser. `:has` is just fine from CSS parsing common rules. All the rest is a responsibility of lexer or similar. Moreover, a validation of CSS syntax is usually performing on token's level, not AST. So that's by design and a selector validation will be opt-in once implemented in the lexer.
