### ISSUE TITLE
Empty argument pseudos such as `:has()` throw

### ISSUE THREAD

**Issue by bramus** [csstree/csstree#219]
When parsing `:has` with the context of a `selector` it works fine:

```json
{
    "type": "Selector",
    "loc": null,
    "children": [
        {
            "type": "PseudoClassSelector",
            "loc": null,
            "name": "has",
            "children": null
        }
    ]
}
```

When parsing `:has()` however, it does not:

```
❌ SyntaxError: Selector is expected
```

I expected the output here to be the same in both cases. Is this something that’s feasible to be fixed? I can take a look into it if wanted.

Demo: https://codepen.io/bramus/pen/NWzQqdp/c8766b9b857cf1637f254a16269a5848

**Comment by lahmatiy** [comment]
I think that a parser should be abstract enough. So `:has()` should be parsed just fine, despite that a spec requires a selector list. For now, CSSTree parser expects a selector list for `:has()` ([source](https://github.com/csstree/csstree/blob/master/lib/syntax/pseudo/index.js#L35)). I suppose, we could relax it as well as for other pseudos. There are two to achieve it:
- Relax pseudo parsing to allow empty `children`. It can't be `children: null` for both `:has` and `:has()`, because when `children` property is `null` it's a pseudo class (i.e. `:has`), otherwise it's a functional pseudo class (i.e. `:has()`). So for `:has()` it could be just an empty list.
- An alternative way is to relax `SelectorList` parsing to allow its `children` to be an empty list. But I don't think that's a good idea since an empty selector list looks odd.

I prefer a relaxing of pseudos parsing. That's can be achieved by altering a `parse` method for each known pseudo. However, a better way to alter `parse` methods for `PseudoClassSelector` and `PseudoElementSelector` to use custom pseudo parsing only when a functional pseudo is not empty, otherwise use an empty `List` for `children`. For instance, in [this block](https://github.com/csstree/csstree/blob/master/lib/syntax/node/PseudoClassSelector.js#L25) before a pseudo class name check we can test if a next non-comment/whitespace (`this.lookupTypeNonSC(0)`) token is `<)-token>` then use an empty list for children.
