### ISSUE TITLE
How to do getComputedStyle for a list of classes?

### ISSUE THREAD

**Issue by mblais** [csstree/csstree#269]
What's the best way to get the combined/computed style of a particular list of classes?

**Comment by lahmatiy** [comment]
That's a complex problem and generally impossible to achieve if your target is not a single browser with a specific version.

First, you need to split shorthand declarations into simple declarations, then combine rule blocks based on value correctness and browser support. Additionally, it's challenging to determine if two property values are the same to eliminate duplicates. The main difference between a static merge (based solely on source code) and a browser's getComputedStyle is that you often can't obtain a single value for a property due to differences in support across browsers and their versions.
