### ISSUE TITLE
`MediaQuery`  node not returning modifier

### ISSUE THREAD

**Issue by thescientist13** [csstree/csstree#285]
Was testing an upgrade to the [3.0.0 release](https://github.com/csstree/csstree/releases/tag/v3.0.0) and was refactoring for the `MediaQuery` node and noticed that the `modifer` property was not being returned?  Not sure if am doing something wrong or misunderstanding something here (which is entirely possible 😅 )

Given this CSS, taken from [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#syntax)
```css
@media screen and (min-width: 900px) {
  article {
    padding: 1rem 3rem;
  }
}
```

I would have expected the value of `modifier` to be **and**, but it is `null`
```sh                                       
{
  node: {
    type: 'MediaQuery',
    loc: null,
    modifier: null,
    mediaType: 'screen',
    condition: { type: 'Condition', loc: null, kind: 'media', children: [List] }
  }
}
```

----

I made a demo repo here to reproduce the behavior - https://github.com/thescientist13/css-tree-media-query-modifier-demo

Thanks!

**Comment by lahmatiy** [comment]
@thescientist13 The `modifier` property is used for the `not` and `only` keywords, which precede `mediaType`. The `and` keyword is used when both `mediaType` and `condition` are present. Since this is the only valid conjunction between `mediaType` and `condition` for correct syntax (see [Media Queries](https://drafts.csswg.org/mediaqueries/#mq-syntax)), I didn't see the need to store it explicitly in the AST.

<img width="736" alt="image" src="https://github.com/user-attachments/assets/4bd4043d-dd91-4f5f-8cf8-141f15a67f3b">

You can also refer to the `MediaQuery`'s `generate` method to see how it constructs the CSS, which is a bit simpler than following the parsing logic: https://github.com/csstree/csstree/blob/9de5189fadd6fb4e3a149eec0e80d6ed0d0541e5/lib/syntax/node/MediaQuery.js#L86-L100

It's worth noting that the `and` between `mediaType` and `condition` is different from the `and` used within a `condition`, where both `and` and `or` can be explicitly represented as `Identifier` nodes in the AST. The parser doesn't validate the syntax of the `condition`; it simply consumes and constructs all valid nodes, such as `Identifier`, `Function`, nested `Condition`, `GeneralEnclosed`, `Feature`, etc. This means it even consumes invalid syntax like `screen and (and and and)`.

This approach is intentional to allow other tools to validate or transform the AST structure and fix issues by operating directly on AST nodes rather than on the string representing the `@media` prelude (media query). If you need to ensure a media query is valid before processing its AST, you can use one of the following methods:

```js
lexer.matchAtrulePrelude('media', ast);  // You can also pass a string instead of the AST
lexer.matchType('media-query-list', ast);
lexer.matchType('media-query', ast);
```

**Comment by thescientist13** [comment]
> The modifier property is used for the not and only keywords, which precede mediaType. The and keyword is used when both mediaType and condition are present.

Ah, ok thanks for clarifying that and providing the extra context.   With that insight in hand, I was able to get what I needed working as I needed.

Thank you!  ✌️
