### ISSUE TITLE
Parsing known vs unknown functions in `@supports`

### ISSUE THREAD

**Issue by bramus** [csstree/csstree#295]
When parsing the following CSS with csstree 3.0.0 it treats the functions inside `@supports` differently

```css
@supports (selector(*)) { }
@supports (inexistent(thing)) { }
```

The `selector` function is parsed as a `FeatureFunction`, whereas the `inexistent` function becomes a `GeneralEnclosed`. I would have expected both to be of the `FeatureFunction` type.

DEMO: https://codepen.io/bramus/pen/PoMOKGe/d3779206b578d094239d977c9699bae0?editors=0010

**Comment by lahmatiy** [comment]
@bramus That's how CSS defines [`<supports-condition>`](https://drafts.csswg.org/css-conditional-3/#at-supports), and the `selector()` function is a recognized function [defined ](https://drafts.csswg.org/css-conditional-4/#at-supports-ext) in Conditional Rules 4. On the other hand, `inexistent()` is not a known function. According to the spec, it falls back to a general enclosure, meaning that its content is treated as opaque since the CSS parser does not know how to interpret it.

If you want to introduce a new function like `inexistent()`, you can do so by defining it as a `@supports` feature. The standard features are listed in CSSTree [here](https://github.com/csstree/csstree/blob/master/lib/syntax/config/parser.js#L29-L40). For your case, you need to use `fork()` method to "fork" the CSSTree syntax and extend the `features.supports` to include your custom function.

Here's an example of how to achieve this:

```js
import * as csstree from "https://esm.sh/css-tree@3.0.0";

console.clear();

const css = `@supports (selector(*)) { }
@supports (inexistent(thing)) { }`;

// parse CSS to AST
const alteredSyntax = csstree.fork({
   features: {
      supports: {
         inexistent() {
            // Here, you need to parse the content of the custom function.
            // If the function does not consume all its content before the closing parenthesis
            // or throws an error during the parsing, the function's content will become a Raw node.
            // However, the function itself will be represented as a FeatureFunction node
         }
      }
   }
});
const ast = alteredSyntax.parse(css);

// traverse and modify the AST if needed
console.log(JSON.stringify(ast, null, 4));
```

This approach allows to handle custom functions it in the AST as a `FeatureFunction`.

**Comment by bramus** [comment]
Thanks for the clarification and the code example, I appreciate it very much you taking time to clearly explain this.

Closing, as it’s PEBKAC :)
