### ISSUE TITLE
PostCSS (css-loader, Stylelint, CSSModules)

### ISSUE THREAD

**Issue by michael-ciniawsky** [csstree/csstree#38]
👋 I'm watching this awesome project for a while now and wonder if it would be possible to use with PostCSS in some way or another, especially with the fresh alpha17 (extensibility) release? Would it basically be possible ?

**Comment by michael-ciniawsky** [comment]
Thx in advance 😛

**Comment by lahmatiy** [comment]
@michael-ciniawsky It depends on what you expect from using CSSTree with PostCSS.
Right now you can use [stylelint-validator](https://github.com/csstree/stylelint-validator) plugin for stylelint. (In this plugin I make my first [experiments with syntax extensibility](https://github.com/csstree/stylelint-validator/blob/master/syntax-extension/index.js) for less/scss, it may be improved with alpha17)
I would like to experiment with CSS Modules syntax (there is an [issue](https://github.com/csstree/stylelint-validator/issues/5) in stylelint-validator about it, I'm going to fix it) and maybe try to re-implement css-loader using CSSTree one day. Unfortunatelly have no time for this right now.

**Comment by michael-ciniawsky** [comment]
Mainly parsing custom syntaxes like SASS/Less and the speedups :) With a Tree Adapter  usage would be possible now ? In terms of custom AtRules, acknowledging whitespace :) I've seen there is already a Issue open about PostCSS so feel free to close this one here. PostCSS support would be awesome nevertheless, it's basically just the shell to make a plugeable Parser possible and it has already a broad community. Before reimplementing `css-loader` open an issue instead I'm current maintainer @css-loader 😛

**Comment by lahmatiy** [comment]
> Mainly parsing custom syntaxes like SASS/Less and the speedups :)

Well, SCSS and Less parsing is possible by using `postcss-scss` and `postcss-less` syntaxes. But there is a problem that PostCSS has only 6 node types and some constructions (like variable declarations) can't be represented with that set of nodes. For the same reason, a converting from CSSTree AST format to PostCSS format is tricky as well.

If we talk about speedups, I'm not sure it will be significant. Yes, parsing may be faster, but then we need to convert CSSTree AST to PostCSS format - it takes some time. Translating into string will on PostCSS side, no benefits here. Moreover, most time of any PostCSS pipeline consumes by tree traversal and AST transformations, and that's also on PostCSS side and no any effect on using CSSTree here too.

> With a Tree Adapter usage would be possible now ?

Yep, it's possible. Converters in [postcss-csso](https://github.com/lahmatiy/postcss-csso/tree/master/lib) may be used as a basis for this kind adapter. But this a problem to make universal converter if we think about extensibility. Currently `postcss-csso` expects a specific set of node types, extensions or future changes of this set may break everything. Have no idea how to make it universal at this point.

> In terms of custom AtRules, acknowledging whitespace

Not sure I'm got it correct. Could you clarify?

> I've seen there is already a Issue open about PostCSS so feel free to close this one here. PostCSS support would be awesome nevertheless, it's basically just the shell to make a plugeable Parser possible and it has already a broad community.

It's ok to keep this issue opened since mentioned discussion had gone in another direction ;)
I agree that PostCSS is a great tool, very popular, so on. But this doesn't mean that we should make integration with it as the main goal. I'm ok if CSSTree never to be popular as PostCSS, but no competition here. PostCSS has some limits and pressure by backward capability. I think it's a blocker for significant changes.

So I'm seeking for better solutions for common tasks and solve complex problems, as it should be, with no limits. Not all problems are solved yet, but there some positive results that give me believe it will be done one day, soon or later.

I also see that CSSTree and PostCSS have got quite different concepts, so I'm not sure they can be integrated well or merged in future. But who knows? At least things like `stylelint-csstree` and others are possible already, maybe it will be enough.

> Before reimplementing css-loader opening an issue instead would be appreiated I'm current maintainer @css-loader 😛 .

Wow, cool :)
Anyway, I would like to experiment first to understand the task is possible. Current blocker is CSSTree is losing original formatting. I don't know how it important is (to keep formatting). Nevertheless, I would like to improve CSSTree to make possible CSS restoring with original formatting. Then try to implement `css-loader` with CSS Modules support. The main goal of it to find weaknesses in CSSTree that should be addressed.

> During this fact I'm also interested in improvements to CSSModules but that's off topic here, I don't want to bother you here

Feel free to ask questions here, at another issue or place. It's interesting to me what improvements you are talking about ;)
