### ISSUE TITLE
atruleExpression always null

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#39]
The this.atruleExpression is always null, even with Atrule expressions, even not inside an Atrule expression.
There isn't any node of type 'atruleExpression' or of similar name either.
It would be very convenient if the atruleExpression is available for all its child nodes.

```js
var csstree  = require('css-tree');

var testCss = '@media screen{.st1{fill:red;}}';
var cssAst = csstree.parse(testCss);
csstree.walk(cssAst, function(node, item, list) {
  // this.atruleExpression is always null, even inside node with type == 'Atrule'.
});
````

**Comment by lahmatiy** [comment]
Yep, it's because `Atrule.expression` is `MediaQueryList` type, not an `AtruleExpression`. Not sure it's a bug, but agree it's confusing.
I'm planning to change solution to provide access to upper nodes (via the stack or something like that). But still thinking about a better way for that.
Until new solution I added `contextWalker` marker for `MediaQueryList`, it should help right now. Will publish patch version later.

**Comment by strarsis** [comment]
The reason is that I want to filter selectors by their parent Atrule expression (media query), 
this is only possible when the parent Atrule is known for each selector.

**Comment by lahmatiy** [comment]
Well, for your task you need a `this.atrule` reference rather than a `this.atruleExpression`. We need to add this marker also. That's why I dislike current solution.
Yep, you need wait until next release. Or use `csstree/csstree` in you `package.json` instead of version (in this case, csstree will be installed from `master` branch).

**Comment by lahmatiy** [comment]
I added `this.atrule` reference in context. Also, I've created an issue #41 to track status on changes in walker implementation.

**Comment by lahmatiy** [comment]
Start with `1.0.0-alpha20` at-rule prelude is always wraps into AtruleExpression. So `this.atruleExpression` now works as expected.
