### ISSUE TITLE
Ability to merge AST trees

### ISSUE THREAD

**Issue by peterbe** [csstree/csstree#53]
Perhaps this is an implementation issue and not a valuable feature request within csstree. 

I would like to be able to merge AST trees. My context is to generate a minimal CSS payload based on what's used in a DOM, by different DOMs. If DOM1 needs `p, b { X } footer { Y }` and DOM2 needs `p, i {X} header{ Z }` then the combined CSS would be `p, b, i { X } footer { Y }  header { Z }`.

Perhaps an option is to just concatenate them into one big string and use some postCSS plugin or somesuch that can merge/minify it to the minimal set.

**Comment by peterbe** [comment]
The more I think about it, perhaps it's best to keep things simple. 
I can use `csstree` to compute multiple payloads of CSS and use [postcss-merge-rules](https://github.com/ben-eb/postcss-merge-rules) to turn that into 1 CSS payload.

**Comment by lahmatiy** [comment]
Hi, @peterbe!
It's definitely not a task for CSSTree, but for a CSS minifier.
I can suggest [CSSO](https://github.com/css/csso) since it uses CSSTree under the hood and can accept its AST as input. It also has the [usage data](https://github.com/css/csso#usage-data) feature that may be used to strip off unused selectors and rules.

**Comment by peterbe** [comment]
Awesome! I didn't know about CSSO. Let's close this issue.
