### ISSUE TITLE
"LeftCurlyBracket is expected" error when using parseSelector: false

### ISSUE THREAD

**Issue by davidkudera** [csstree/csstree#56]
Hi, I wanted to parse some styles with `parseSelector: false`, but when I do that I see following error: 

```
Parse error: LeftCurlyBracket is expected
    1 |div {}
-------------^
```

**Steps to reproduce:**

```bash
$ mkdir css-test && cd css-test
$ npm install css-tree
```

Create `index.js` file with this code:

```javascript
var parse = require('css-tree').parse;

try {
	var ast = parse('div {}', {
		parseSelector: false
	});

	console.log(ast);
} catch (e) {
	console.log(e.formattedMessage);
}
```

and run

```bash
$ node index.js
```

-------------------------------

Interesting is that when I clone this repository and try to write the code above as test, it works just fine.

**Versions**: both `1.0.0-alpha22` and 171664aaf7bfb8d2973c031b2568a2f440bd05bd.

**Comment by peterbe** [comment]
I get this too

```
> const csstree = require('css-tree')
undefined
> const text = `body, p { font-weight: bold; }
... body { border: 1px solid red; }
... `
undefined
>
> const ast =csstree.parse(text, {parseValue: false, parseSelector: false})
CssSyntaxError: LeftCurlyBracket is expected

> csstree.parse(text.trim(), {parseValue: false, parseSelector: true})
{ type: 'StyleSheet',
  loc: null,
  children:
   List {
     cursor: null,
     head: { prev: null, next: [Object], data: [Object] },
     tail: { prev: [Object], next: null, data: [Object] } } }

```

**Comment by lahmatiy** [comment]
Your case let me to confirm a problem that I could not reproduce in the tests. It's a bit complicated and all around balance finding in tokenizer (can be reproduced only when token count less that input length; my test case was `? { }` – input length equal to token count).
You could not reproduce the problem it in the tests because parser re-use tokenizer and last one re-use buffers. Therefore previous tests "fix" up your test by data left in the buffer.
Never mind... now it fixed, release is coming.
Good finding. Thank you!

**Comment by davidkudera** [comment]
awesome, thank you 👏

**Comment by lahmatiy** [comment]
[1.0.0-alpha23](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha23) with fix is out :)
