### ISSUE TITLE
How to distinguish Declarations?

### ISSUE THREAD

**Issue by ahmedk92** [csstree/csstree#61]
I was walking declarations by font-family; like this:

```
csstree.walk(ast, function(node) {
		if (node.type === 'Declaration' && node.property === 'font-family') {
			
			var valueNode = JSON.parse(JSON.stringify(node.value));
			for(var i = 0; i < valueNode.children.length; i++) {
				if (valueNode.children[i].value === '\"myfont\"') {
					node.important = true;
					console.log(JSON.stringify(node));
				}
			}
		}
});
```

It's working. But I get two results. One for the `@font-face`, and one for the class declaration I really want. The node model for both is identical. How to distinguish?

Btw, thank you for the amazing project!

**Comment by lahmatiy** [comment]
At the moment, you can check you're not inside `@font-face` at-rule:
```js
if (this.atrule !== null && this.atrule.name.toLowerCase() === 'font-face') {
    return;
}
```

Some tips:
- normalize names via `.toLowerCase()` or [`csstree.property()`](https://github.com/csstree/csstree/blob/master/docs/utils.md#propertyname) helper
- use [`csstree.toPlainObject()`](https://github.com/csstree/csstree/blob/master/docs/utils.md#toplainobjectast) instead of `JSON.parse(JSON.stringify(node.value))`
- you don't need convert `valueNode.children` to an array. `children` is a List, use its API:
```js
var valueNode = JSON.parse(JSON.stringify(node.value));
for(var i = 0; i < valueNode.children.length; i++) {
    if (valueNode.children[i].value === '\"myfont\"') {
       // ...
    }
}
// ->
node.value.children.each(function(child) {
    if (child.value === '\"myfont\"') {
        // ...
    }
})
```
- it's maybe better to use `findValueFragments()` or `findDeclarationValueFragments()` to find things like a family-name, see [example in tests](https://github.com/csstree/csstree/blob/master/test/lexer.js#L499-L504) (will be described in docs later)

**Comment by ahmedk92** [comment]
Thank you! It worked.
