### ISSUE TITLE
negative value for max-height is not meant to be valid

### ISSUE THREAD

**Issue by twig-openlearning** [csstree/csstree#97]
result on https://csstree.github.io/docs/validator.html
![image](https://user-images.githubusercontent.com/11620855/54660238-b42b7500-4b29-11e9-990b-e9e4f30bfa76.png)

testing the same CSS on https://jigsaw.w3.org/css-validator/validator
![image](https://user-images.githubusercontent.com/11620855/54660261-d4f3ca80-4b29-11e9-9c28-c572e832181a.png)

**Comment by revelt** [comment]
The spec of CSS Media Queries Level 4 (dated 2017 September) have changed slightly and negative values are now allowed, differently from Level 3:

> "This is a behavior change compared to Media Queries Level 3 [MEDIAQ], where negative values on these properties caused a syntax error. In level 3, syntax errors—including forbidden values—resulted in the entire media query being false, rather than the unknown treatment defined in this level. Implementations updating from level 3 should make sure to change the handling of negative values for the relevant properties when they add support for the richer syntax defined in §2.5 Combining Media Features, to avoid introducing unintended semantics."
https://www.w3.org/TR/mediaqueries-4/#mq-range-context

Also,

> "Some media features with a "range" type are said to be false in the negative range. This means that negative values are valid and must be parsed, and that querying whether the media feature is equal to, less than, or less or equal than any such negative value must evaluate to false."
https://www.w3.org/TR/mediaqueries-4/#false-in-the-negative-range

The validator in the screenshot shows it's "CSS Level 3 + SVG". Theoretically, our parser is correct. A negative value will yield a falsey media query that that's allowed. However, from user's perspecitve, a linter should catch that (possibly driven by this very parser).

I suggest we close this issue.

**Comment by lahmatiy** [comment]
CSSTree validation is based on syntax definition dictionaries from [mdn-data](https://github.com/mdn/data) which based on CSS specs. Such syntax definitions are not complete and don't cover all the nuances, some things are describing in prose not in a syntax definition. However, there is a [Range Restrictions and Range Definition Notation](https://www.w3.org/TR/css-values-4/#numeric-ranges) which might help with issues like this one. But it's quite a new addition to the definition syntax and is not yet widely used in the CSS specs.

In such cases we should start with a suggestion to an appropriate spec ([CSSWG specs repo](https://github.com/w3c/csswg-drafts/)). If it will be accepted, then we need to change a syntax definition in `mdn-data`. So will it go upstream to CSSTree and its validation. In some cases we can fix the problem with a syntax using a [definitions patch](https://github.com/csstree/csstree/blob/master/data/patch.json). But this is not the case.

Closing the issue since it's out of scope the library itself.
